# Deploy otel instrumentation image to GitHub container registry
name: Deploy otel instrumentation image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - apps/otel-instrumentation/**
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build image"
        run: |
          docker build . --tag ghcr.io/adaptivekind/example-otel-instrumentation:latest
          docker push ghcr.io/adaptivekind/example-otel-instrumentation:ubuntu-latest
