# Deploy otel instrumentation image to GitHub container registry
name: Deploy otel instrumentation image

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/otel-instrumentation
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.ACCESS_TOKEN}}

      - name: "Build and deploy image"
        uses: docker/build-push-action@v6
        with:
          file: apps/otel-instrumentation/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: example-otel-instrumentation:latest
