name: Deploy OTEL Express image

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.ACCESS_TOKEN}}

      - name: "Build and deploy image"
        uses: docker/build-push-action@v6
        with:
          context: ./apps/otel-instrumentation-express
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/adaptivekind/example-otel-instrumentation-express:latest
